### ISSUE TITLE
Unable to add connection

### ISSUE THREAD

**Issue by jazucco-oeis** [Sheeley7/vscode-webrm#10]
Using the latest version of Visual Studio Code (v1.79.2)

I receive the following error when trying to create a connection: 

Error running command wrm.addConnection: command 'wrm.addConnection' not found. This is likely caused by the extension that contributes wrm.addConnection.

**Comment by Sheeley7** [comment]
Can you verify that your extension settings are set correctly?

You will need to fill in the the first and third definitely, and maybe the second depending on how you setup your app registration in Azure.

![image](https://github.com/Sheeley7/vscode-webrm/assets/5257942/0adadde1-b6c9-40d6-832f-195f27f97119)

**Comment by jazucco-oeis** [comment]
I've been playing around with those settings. In my case I'm hoping to use this extension to edit web resources for a Dynamics 365 Model Driven app. Perhaps that's part of the issue, does this extension only support Azure apps? 

If it does support Dynamics applications, what would be the expected value for the App Client ID?

**Comment by Sheeley7** [comment]
> I've been playing around with those settings. In my case I'm hoping to use this extension to edit web resources for a Dynamics 365 Model Driven app. Perhaps that's part of the issue, does this extension only support Azure apps?
> 
> If it does support Dynamics applications, what would be the expected value for the App Client ID?

This extension is specifically designed for Dynamics 365. The Azure app registration is for allowing authentication to your Dynamics environment with the extension. The guide below shows you how to setup an Azure App registration and configure it to allow Dynamics 365

https://learn.microsoft.com/en-us/power-apps/developer/data-platform/walkthrough-register-app-azure-active-directory

**Comment by jazucco-oeis** [comment]
Thanks, much appreciated, up and running now.
